// Account Settings
// export const CHANGE_PASSWORD = {
//     ATTEMPT: 'CHANGE_PASSWORD_ATTEMPT',
//     FAILED: 'CHANGE_PASSWORD_FAILED',
//     RESET: 'CHANGE_PASSWORD_RESET',
//     SUCCEED: 'CHANGE_PASSWORD_SUCCEED'
// }

export const GET_CONTACT = {
    ATTEMPT: 'GET_CONTACT_ATTEMPT',
    FAILED: 'GET_CONTACT_FAILED',
    SUCCEED: 'GET_CONTACT_SUCCEED'
}


export const GET_CONTACT_ID = {
    ATTEMPT: 'GET_CONTACT_ID_ATTEMPT',
    FAILED: 'GET_CONTACT_ID_FAILED',
    SUCCEED: 'GET_CONTACT_ID_SUCCEED'
}

export const DELETE_CONTACT = {
    ATTEMPT: 'DELETE_CONTACT_ATTEMPT',
    FAILED: 'DELETE_CONTACT_FAILED',
    SUCCEED: 'DELETE_CONTACT_SUCCEED'
}

export const ADD_CONTACT = {
    ATTEMPT: 'ADD_CONTACT_ATTEMPT',
    FAILED: 'ADD_CONTACT_FAILED',
    SUCCEED: 'ADD_CONTACT_SUCCEED'
}


export const PUT_CONTACT = {
    ATTEMPT: 'PUT_CONTACT_ATTEMPT',
    FAILED: 'PUT_CONTACT_FAILED',
    SUCCEED: 'PUT_CONTACT_SUCCEED'
}

